apiVersion: integration/v1
kind: Step
name: timeline-update
version: 1
summary: Update a FireHydrant.io incident timeline from Relay

description: |
  This step will post information back into the FireHydrant.io
  incident response service from a Relay workflow. It requires
  the UUID of the incident as a parameter to associate the
  update correctly, as well as your apiKey (as a Secret) to
  authenticate against the FireHydrant REST API.

publish:
  repository: relaysh/firehydrant-step-timeline-update

# optional list of examples; each one can be a Step or a complete Workflow
examples:
- summary: Update an incident timeline
  apiVersion: v1
  kind: Step
  name: timeline-update
  image: relaysh/firehydrant-step-timeline-update
  spec:
    apiKey: !Secret apiKey
    incidentID: !Secret incidentID
    message: "Relay ran a workflow and fixed the problem"

schemas:
  spec:
    $schema: http://json-schema.org/draft-07/schema#
    type: object
    properties:
      message:
        type: string
        description: The message to post to the API
      apiKey:
        type: string
        description: An API token from FireHydrant Bot Users setup
      incidentID:
        type: string
        description: The internal UUID of the Incident to update
